services:
  - type: web
    name: my-notes-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn notes.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: notes-db
    plan: free
